apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Hello world test component
spec:
  type: service
  lifecycle: experimental
  owner: development
