apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: local-test-template
  title: Local Test Template
  description: This template is for local testing without pushing to GitHub.
spec:
  owner: development
  type: service

  parameters:
    - title: Project Information
      required:
        - name
      properties:
        name:
          type: string
          title: Project Name
          description: The name of your project

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.name }}
        repoUrl: github.com?owner=limhoooo&repo=${{parameters.name}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    text:
      - title: "🎉 Template Test Completed!"
        content: "Project '{{ parameters.name }}' has been created. Download it from the UI."
